### ISSUE TITLE
Suggestion: Additional Heavenly Chips Information

### ISSUE THREAD

**Issue by ender2021** [greenc/CookieMaster#10]
In addition to the cookies remaining for the current chip, it would be useful to be able to see the total number of cookies the current chip will cost.  It could also be useful to see the total time it took to acquire the last chip.

**Comment by greenc** [comment]
Total number of cookie for next chip has now been added. Total time to acquire last chip would be irrelevant in a large number of cases since many factors can greatly skew this stat for each chip.
