### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gooray** [greenc/CookieMaster#107]
I've tried installing cookie master as an extension and using the bookmark method - neither works and the addon won't open at all.

**Comment by rashfael** [comment]
Did you use the correct bookmarklet? The one on the website is obsolete, [this is the current one](https://github.com/greenc/CookieMaster#how-to-use).

**Comment by gooray** [comment]
Yes.

**Comment by rashfael** [comment]
Is there any error output on the Developer Console? (Press F12, then load CookieMaster).

**Comment by ghost** [comment]
It's not working for me either.

```
Uncaught SyntaxError: Unexpected token else cookiemaster.min.js:1
CM.replaceNative cookiemaster.min.js:1
(anonymous function) cookiemaster.min.js:3
```

**Comment by gooray** [comment]
Fixed it - just had to disable the old extension. Thanks for the help.

**Comment by ghost** [comment]
The bookmarklet works.
