### ISSUE TITLE
Memory leak and CPU churn

### ISSUE THREAD

**Issue by Stanzilla** [greenc/CookieMaster#123]
After a while, the tab process in chrome is using over 1,2gb of memory and around 13% CPU.

Looking at the console shows this

http://i.imgur.com/xg4VELD.png

Getting spammed every second.
From guessing from the name, it suggest that a extension might be causing it, though

**Comment by Stanzilla** [comment]
Currently suspecting @gorhill 's ublock (https://github.com/gorhill/uBlock)

**Comment by gorhill** [comment]
From the screenshot I can tell that uBlock was disabled then re-enabled after a tab had been injected with its content scripts. Thus the messaging port on the content script side is dangling -- it lost connection to uBlock (because it was disabled). It's an anomalous state, I suspect because you are trying to debug something?

**Comment by Stanzilla** [comment]
I didn't really disable it, maybe it reloaded itself after I injected the CookieMaster snippet via 

``` javascript
javascript:with(document)(head.appendChild(createElement('script')).src='//cookiemaster.creatale.de/b?c='+Date.now())._
```

?

**Comment by gorhill** [comment]
It could happen I suppose if there is an update -- I didn't think of this case... So I need to accept that a dangling port is a possibility under normal usage. I don't know about CookieMaster... it's a long lived web page?

**Comment by gorhill** [comment]
Re. the snippet, where do I paste it?

**Comment by Stanzilla** [comment]
Oh, it's actually a browser game called Cookie Clicker, located at http://orteil.dashnet.org/cookieclicker/

Cookie _Master_ is a script that enhances the page and is usually injected via the script I linked.

**Comment by Stanzilla** [comment]
project is dead
