### ISSUE TITLE
Stop using rawgithub.com

### ISSUE THREAD

**Issue by llbit** [greenc/CookieMaster#13]
I found this notice on rawgithub.com:

> Use this for testing and for sharing demo code with friends, but don't use it for anything production-related.

**Comment by greenc** [comment]
I'm aware of this. I'm looking into moving the plugin to another host.

On 15 January 2014 20:13, Jesper Öqvist notifications@github.com wrote:

> I found this notice on rawgithub.com:
> 
> Use this for testing and for sharing demo code with friends, but don't use it for anything production-related.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/greenc/CookieMaster/issues/13
> .

## 

Chris Green
Tel: +44 2036 851683
Mob: +44 7445 306964
Skype: chrisNWD

**Comment by greenc** [comment]
Fixed.
