### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by xandermanderpi** [greenc/CookieMaster#18]
Currently using Chrome, and my browser ended up blacklisting http://rawgithub.com/greenc/CookieMaster/master/build/cm-bootstrap.min.js?cb=10ck8. This creates a 403 whenever I try to run Cookie Master. This is a personal laptop at home. Can someone please tell me how to unblacklist the URL?

**Comment by greenc** [comment]
CookieMaster has since moved host in response to being blacklisted from rawgithub.com. Please update your bookmark with the new location to fix the issue:

``` javascript
javascript:(function(d){d.body.appendChild(d.createElement('script')).setAttribute('src','//greenc.github.io/CookieMaster/build/cm-bootstrap.min.js?cb='+Math.random().toString(36).substr(2,5))})(document)
```

**Comment by xandermanderpi** [comment]
Thanks.
