### ISSUE TITLE
Current Lucky and Lucky+Frenzy Reward Incorrect

### ISSUE THREAD

**Issue by llbit** [greenc/CookieMaster#2]
When the grandmatriarchs are appeased or not yet awoken the Lucky and Lucky+Frenzy rewards are not calculated correctly. CookieMaster displays the same current reward as the maximum, even if the maximum is not same as the current.

![bug](https://f.cloud.github.com/assets/2757386/1832127/c3b3ea60-73a8-11e3-8d0c-5ac4f01ae17b.png)

**Comment by greenc** [comment]
Fixed in v1.4.2 release.
