### ISSUE TITLE
Suggestion: Frenzy+Click Frenzy Alert

### ISSUE THREAD

**Issue by skyshineb** [greenc/CookieMaster#20]
Sound alert and Tab title change. When i hear sound i switch to game tab and autoclicker will work. To avoid loosing such big amount of CpC.

**Comment by greenc** [comment]
I'm not sure I understand your request. Can you explain in a little more detail?

**Comment by skyshineb** [comment]
I'am sorry) Situation:Autoclicker in setting is on.The game works in a background tab. CookieMaster clicks on gold cookies and reindeers, but not on a big cookie(because working in background). It is possible that I will get a combination of effects: Frenzy and Click Frenzy from the golden cookies. Amount of Cookies per Click will very big. But I didn't know about it. But if possible to create a sound notification for this effect combination or single Click Frenzy effect, it will be good. I do what i want on my PC and if i hear this sound i will switch on the game and the autoclicker start working, as a result i get a really big amount of cookies.
Sorry for my bad english)

**Comment by greenc** [comment]
I understand now :)

As you probably know, Chrome limits background tab timers to 1000ms, so it will only click the Big Cookie 1 time per second in background mode.

I could make a feature that alerts you if a Frenzy+Click Frenzy happens so you can switch to the tab and click faster.

I think most users do not understand this limitation though, so for now I will simply add an explanation in the settings that while running in a background tab, the auto-clicker will be slower.
