### ISSUE TITLE
Timers disapear

### ISSUE THREAD

**Issue by drewgle** [greenc/CookieMaster#21]
Timers disappear after they run out once. They can be brought back by applying changes.

**Comment by greenc** [comment]
I can't seem to replicate this. Can you specify what browser and OS you're on? Are you using the Chrome extension, userscript or bookmark to load the plugin?

**Comment by drewgle** [comment]
I've seen this with two computers. One running win7, chrome and the bookmark, the other win 8.1 and FireFox.
![ccapture](https://f.cloud.github.com/assets/6296001/2087108/75dfc930-8e65-11e3-9423-8544b7754d72.PNG)

**Comment by greenc** [comment]
Most odd indeed. I have tested thoroughly on Chrome, FF and IE on Win7 and cannot replicate this at all. Can you see if there are any error in the console?

**Comment by drewgle** [comment]
Nothing significant in the console but after watching it for a while I noticed that it only happens when the cookie clicker tab is in the background as it auto clicks the golden cookie or reindeer.

**Comment by greenc** [comment]
I think I have fixed the bug, but I had trouble reproducing it consistently, although I did manage to see it in effect a few times when I tested.

v.1.11.5 has the patch, and is live across all delivery methods.

Feel free to reopen this issue if the bug persists.
