### ISSUE TITLE
Version update notification gives wrong instructions for Chrome extension users

### ISSUE THREAD

**Issue by jameslittle230** [greenc/CookieMaster#22]
https://github.com/greenc/CookieMaster/blob/master/src/cookiemaster.js#L3497

The manually update extensions button does not appear unless you're in developer mode, which most users are not.

**Comment by greenc** [comment]
Good point, I always have it checked and forget that normal users can't see the option. I'll amend the message :)

**Comment by greenc** [comment]
Fixed in v.1.11.6
