### ISSUE TITLE
Valentine's Day Upgrade Breaks CookieMaster

### ISSUE THREAD

**Issue by musiKk** [greenc/CookieMaster#23]
You're probably already aware of this but just in case: The Valentine's Day update (1.0411) breaks CookieMaster almost completely. A few minor things still work such as number formatting on prices but options and stats+ are inaccessible.

**Comment by jsutan** [comment]
Here's just some of the things that are no longer working:
- Auto-click no longer working, Auto-click Golden Cookies/Reindeer no longer working, Auto pop Wrinklers no longer working.  Pretty much anything that was an option in the Settings page isn't working except number shrinking and number font.
- Various timer bars no longer displaying
- Building deficit tooltip assist no longer displaying values
- Unknown values for the new building (Prism)
- Unknown values for the new upgrades
- Stats + and Settings are not clickable

**Comment by RuiApostolo** [comment]
After a refresh, number shortening only works after buying one building.
Building coloring doesn't work.

**Comment by greenc** [comment]
Should be fixed in v.1.12.3 :)

**Comment by musiKk** [comment]
That was fast. Thanks! :cocktail:
