### ISSUE TITLE
"Festive biscuit" missing upgrade

### ISSUE THREAD

**Issue by shrx** [greenc/CookieMaster#24]
CookieMaster v.1.13.0 reports that I have a "Festive biscuit" upgrade missing. I can't find info about this upgrade on the [wiki](http://cookieclicker.wikia.com/wiki/Upgrades) and it doesn't add up to the total upgrades count (the regular Stats page reports two upgrades missing, which corresponds to two Halloween cookies).

**Comment by greenc** [comment]
Whenever you purchase one of the season-changing upgrades, it will appear in the missing upgrades list. I will look into a fix for this, however :)

**Comment by shrx** [comment]
Oh right, the new season upgrades. I guess the wiki is not updated as fast as CookieMaster :)

**Comment by greenc** [comment]
Fixed in v.1.14.0
