### ISSUE TITLE
No sound for Golden Cookie alerts

### ISSUE THREAD

**Issue by llbit** [greenc/CookieMaster#25]
Can't seem to get the sounds to play for Golden Cookie after the v-day update
- CC v.1.0411
- CM v.1.13.0
- Browser: Chrome

**Comment by greenc** [comment]
Any console errors or messages? Working fine for me (1.13.0 / 1.0411 / Chrome)

**Comment by llbit** [comment]
It works now again, same versions of CC/CM/Chrome. I guess I just did something stupid which disabled the sounds.
