### ISSUE TITLE
Auto-click golden cookie sometimes misses later cookie chain clicks

### ISSUE THREAD

**Issue by jsutan** [greenc/CookieMaster#26]
Auto-click cookies sometimes misses cookies in the cookie chain that are later in the chain since they start spawning and have <1 second to be clicked.  Not sure if that is a bug in the original code (seems like they are semi-random in the later cookie chain clicks where it might be a rounding error rounding up to 1 second or down to close to 0).  But either way, the auto-click misses it.  Not sure if there is an auto-click golden cookie poll interval that can be adjusted (only during chains) or something to that effect.

**Comment by greenc** [comment]
Interesting, I will look into this and possibly move the auto-clicker for popups into the faster refresh loop instead of the default one, which ticks at 1fps.

**Comment by jsutan** [comment]
For what it's worth, it generally happens around the 777 billion cookie click (not sure exactly what number that in the chain that is, 12 I think?)

**Comment by shrx** [comment]
I can confirm this happened to me too.

**Comment by greenc** [comment]
Should be fixed in v.1.14.2
