### ISSUE TITLE
Building tooltip hover does not work on buildings you have not bought at least 1 of

### ISSUE THREAD

**Issue by jsutan** [greenc/CookieMaster#28]
When a new building is unlocked in this new version, the tooltip hover with "Bonus Income", "BCI" etc doesn't display.  Once you buy at least one of the building, though, it works.  Would only be useful for seeing the "Time left" to see how long it would take to buy the building.  The BCI coloring appears to function properly on the building before it is bought, though.

**Comment by greenc** [comment]
Orteil has disabled tooltips for buildings that you haven't bought at least one of. I have decided to respect this design choice for the time being.

I may revisit this at a later point in time, however.
