### ISSUE TITLE
Add confirmation dialog when switching seasons

### ISSUE THREAD

**Issue by jsutan** [greenc/CookieMaster#29]
When you restart the game with high Heavenly Cookie counts it's really easy to spam-click upgrades as they become available and I find it pretty easy to spam click between seasons a few times before I realize I'm doing it.  Mostly a problem since the game doesn't really sort the upgrades very well and sometimes the seasonal is at the beginning, sometimes it's not.

Could you add a dialog box that asks whether you're sure you want to change the season since the price doesn't decrease until you reset the game?

**Comment by shrx** [comment]
+1, as icons for season upgrades are the same as some of the cookies it can be quite misleading.

**Comment by greenc** [comment]
I'm closing this aas wontfix as the new auto-buy feature blacklists season switching upgrades, which covers the use case of accidentally clicking them when on a buying spree.
