### ISSUE TITLE
Feature: Golden Cookies/Reindeer + Wrinklers

### ISSUE THREAD

**Issue by Sejsel** [greenc/CookieMaster#3]
Can you please make clicking Golden Cookies or Reindeer not trigger the wrinklers under them? I sometimes accidentally pop them this way, mostly during Cookie Chains. It is not a bug in your plugin, it happens even without it.

**Comment by greenc** [comment]
Good suggestion. I'll look into it and issue a fix if it's possible

**Comment by greenc** [comment]
This is now fixed in the latest release (v1.5.2).
