### ISSUE TITLE
Out of screen item tooltips

### ISSUE THREAD

**Issue by RuiApostolo** [greenc/CookieMaster#30]
If the item is low on the screen, the item tooltip often becomes partially (or almost completly) out of the screen. This issue is especially problematic on prism's (I have the efficiency key off) because i can't scroll down any more.
![captura de tela 2014-02-16 00 34 28](https://f.cloud.github.com/assets/6303969/2179320/6cebd18a-96a2-11e3-8057-e959849ac67d.png)

**Comment by greenc** [comment]
Fixed in v.1.14.2
