### ISSUE TITLE
CM makes game think you have built and sold one of every building.

### ISSUE THREAD

**Issue by Seifur** [greenc/CookieMaster#31]
When loading version 1.14.0 of the script on a newly wiped game, it causes the game to think you have built and sold one of every building. This awards you with the achievements associated with those conditions and access to upgrades you normally would not have access to yet.

```
MS4wNDExfHwxMzkyNTQ0MjI5MDIyOzEzOTI1NDQyMjkwMzc7MTM5MjU0NTMxODQ1MHwwMDExMDAwMHwwOzA7MDswOzA7MTstMTstMTswOzA7MDswOzA7MDswOzA7MDswOzA7
MDswOzA7dmFsZW50aW5lczt8MCwwLDAsMDswLDAsMCwwOzAsMCwwLDA7MCwwLDAsMDswLDAsMCwwOzAsMCwwLDA7MCwwLDAsMDswLDAsMCwwOzAsMCwwLDA7MCwwLDAsMDsw
LDAsMCwwO3wyNDMwNTE0MDg0NjEwMDU5OzIyNTE3OTk4MTM2OTQwOTE7MjI1MTc5OTgxMzY4NTI0OTsyODE0NzQ5NzY3MTA2NTYxOzIyNTE3OTk4MTM2ODUyNTE7MjI1MTc5
OTgxMzY4NTI0OTsyMjUxNzk5ODEzNjg1MjQ5OzIwOTcxNjN8MzUzOTM2MjMwNjE5NTQ1NzsyMjUyMDc0NjkxNTk2ODczOzQzMTE3NDQ1MTM%3D%21END%21
```

**Comment by shrx** [comment]
That's because of the new code that calculates BCI predictions by actually buying and selling buildings.

**Comment by greenc** [comment]
Should be fixed in v.1.14.1
