### ISSUE TITLE
MultiCookie issues

### ISSUE THREAD

**Issue by goreae** [greenc/CookieMaster#32]
When I load cookieMaster on multiCookie (I use cookie master in a tampermonkey script) the farm and factory have a BCI of zero and nothing else breaks 300, despite the fact that  the most efficient building should have a BCI of around 4500. When the CPS changes, whether it be by a golden cookie effect or buying something, then it reverts to normal. The cookie clicker save stored with the vanilla game is a newly started game.

**Comment by greenc** [comment]
CookieMaster is not designed to be run concurrently with other add-ons. If this issue is reproducible with just CookieMaster running on its own, feel free to reopen the issue with the relevant details.
