### ISSUE TITLE
Lucky and Lucky+Frenzy Calculations

### ISSUE THREAD

**Issue by RuiApostolo** [greenc/CookieMaster#33]
I've noticed that the Lucky and Lucky+Frenzy cookies required calculations in the tooltips take into consideration the added cookies that are required after you buy said item (let me give an example, with made up values, to be more clear).

you got 100 cursors.
lucky + frenzy required bank is 100G
the 101st cursor costs 1G, and increases the lucky + frenzy required bank by 0.5G.

If your bank is empty, the tooltip of the 101st cursor will say you'll need 101.5G cookies to stay above the lucky + frenzy limit.

However, this is not the most efficient way, you should buy the cursor as soon as you get 101G (not 101.5G)

Let me elaborate:

if you buy the 101st cursor as soon as you have 101G, then as your bank increases again, so does the lucky+frenzy reward.

If you wait for the 101.5G, during that time, the lucky+frenzy reward will stay the same until you buy the next cursor.

Please forgive me if I wasn't clear enough, and I'll be glad to answer any question.

**Comment by greenc** [comment]
I think I understand where you're coming from.

You're saying that while the maximum reward will increase, your actual reward would not decrease by purchasing the cursor beforehand (as long as you stay at of above your original max threshold), which in turn gives you more time at the higher CpS which increases your bank faster, to reach the new, higher reward value quicker.

Correct?

**Comment by RuiApostolo** [comment]
exactly. seems I need to work on my synopsis skills :D

**Comment by greenc** [comment]
In theory, this should be a simple change (famous last words), so I'll try and implement it for the next update.

**Comment by greenc** [comment]
Fixed in v.1.15.0
