### ISSUE TITLE
Unavailable buildings taken into account for building colors

### ISSUE THREAD

**Issue by worldendDominator** [greenc/CookieMaster#35]
If an unavailable (blacked out) building has the lowest BCI, all available ones are colored yellow and above.
While it's not a bug, it's somewhat inconvenient because that building won't become available for a while, and you need to check manually to see what you should buy.
So what I'm proposing is to remove hidden buildings from BCI comparison.

**Comment by greenc** [comment]
I can see your point but I think removing unavailable buildings from BCI calculations would be the wrong thing to do.

I will look into making it easier to see the relative BCI so you can easily see the next best building, etc.

**Comment by greenc** [comment]
Closing as wontfix as the auto-buy feature resolves these issues programatically, thus decreasing the scope of the issue.
