### ISSUE TITLE
A number of fixes and suggestions regarding "missing upgrades/achievements" lists

### ISSUE THREAD

**Issue by worldendDominator** [greenc/CookieMaster#37]
1) Most upgrade and achievement descriptions do are on the same line as previous text. Also, they are bolded instead of italic.
2) Both upgrades and achievements go in the order of ID (so that ones added in later versions go last) instead of in-game order.
3) Suggestion: add icons.
4) Suggestion (tentative): add upgrade requirements.

**Comment by greenc** [comment]
1 and 2 have been implemented in v.1.15.0.

3 would probably take up too much space and 4 would be a lot of work for something that is easily found via the wiki.
