### ISSUE TITLE
"Lucky deficit if purchased" warning does not take into account CpS increase

### ISSUE THREAD

**Issue by worldendDominator** [greenc/CookieMaster#39]
Lucky cookie deficit calculation does not take account for CpS increase for buying the building/upgrade in question.
Example: When I mouse over an Antimatter Condenser, the popup says that purchasing it would cause a deficit worth 9 minutes 30 seconds. However, when I buy it, the stats+ screen says it will take 9 minutes 23 seconds. The AC in question added about 2% of my CpS.
Example2: First Prism upgrade (lots of bonus CpS), says 19:56, turns out 18:36.

I hope I understood the case right.

**Comment by greenc** [comment]
Should be corrected now in v.1.15.0
