### ISSUE TITLE
Golden Cookie timer is wrong

### ISSUE THREAD

**Issue by wadde** [greenc/CookieMaster#41]
I know, that the spawn time of golden cookies is random but with all upgrades purchased the displayed time is always between 90 and 120 seconds longer than the real spawn time.
If the displayed time is the max spawn time, than i have never reached it and would prefer the average or minimum spawn time to be displayed.

**Comment by greenc** [comment]
The timer bar reflects the maximum and minimum possible spawn times for Golden Cookies and reindeer, so while the vast majority will spawn at around the middle mark, it is entirely possible for them to spawn at or near the zero values (although unlikely, I agree).

Currently, the average time cannot be calculated without actually tracking real spawns, which is something I may look into if and when I expand on the stats logging feature.
