### ISSUE TITLE
Auto-buy buildings/upgrades

### ISSUE THREAD

**Issue by llbit** [greenc/CookieMaster#42]
It would be nice if there was an auto-buy option which would buy the best upgrade/building as soon as it can be afforded, similar to the auto-clicking popups option.

**Comment by RuiApostolo** [comment]
I have to agreee. Although, as some people might consider it cheating, a disable option is mandatory.

**Comment by greenc** [comment]
It's on my to do list. I need to sort out some BCI calculation bugs beforehand though.

**Comment by greenc** [comment]
Implemented (experimentally) in v.1.16.0
