### ISSUE TITLE
CPS increase after reset

### ISSUE THREAD

**Issue by RuiApostolo** [greenc/CookieMaster#45]
First let me say i loved this new feature.

However (If I'm reading it right), there's a slight error on it, and I'll use mine as an example:

My Base CPS right now (SI notation):903.74 T
CPS after reset: 1.388 P (154% increase)

now, 1.388 P is indeed (roughly) 154% of 903.74 (this is, 903.74 P x 1.54 ~= 1.388)

However, this is an increase of 54% (54% more than 100%, which would be no increase).

So, I would suggest subtracting 100% on the formula.

As an added request, can we please get a couple decimal places on the percentage of increase? It kinda makes me shiver a bit when i do the calculation of CPS after reset by hand and I get a value that's about 20T different from the one CookieMaster calculates.

Thanks a lot for your effort on CookieMaster!!

**Comment by greenc** [comment]
Done and done. v.1.15.1 patch has been released with these fixes.
