### ISSUE TITLE
Display and use "Effective CPS" variable in calculations when Auto-click is enabled

### ISSUE THREAD

**Issue by jsutan** [greenc/CookieMaster#5]
An "Effective CPS" variable would be a nice option to have when Auto-click is enabled that would be calculated as:

effectiveCPS = (clicksPerSecond \* baseCookiesPerCllick) + baseCookiesPerSecond

Using the effective CPS variable will allow you to display to the user how much they're actually making per second with Auto-click turned on as well as create a more accurate  "Time to next HC" value which is inaccurate when Auto-click is turned on.

**Comment by greenc** [comment]
Excellent point, I will try to work this into the next release.

**Comment by greenc** [comment]
Added to next release (v1.5.0).
