### ISSUE TITLE
Lucky+Frenzy Bank not calculating properly

### ISSUE THREAD

**Issue by Casshern1324** [greenc/CookieMaster#52]
Newest update doesn't calculate Lucky+Frenzy Bank after a purchase properly. Is this due to the new way Time Remaining is calculated?

**Comment by greenc** [comment]
It should not be affected by the update. Can you be more specific as to how it's not calculating it properly?

**Comment by Casshern1324** [comment]
The Lucky+Frenzy Deficit timer will hit 0 secs and will say I won't have a deficit at all, warning gone. I'll buy the building/upgrade, and then I'll learn I'm not at my Lucky+Frenzy Bank anymore. As in, I may have an hour or so until then.

**Comment by Casshern1324** [comment]
I don't think it's including the additional CpS from the building/upgrade properly.

**Comment by greenc** [comment]
This is intentional and was part of a previous update. You will now only get a warning if your max lucky reward would be reduced from your current max reward, not the future one after buying the item.

This is more efficient.

**Comment by Casshern1324** [comment]
Damn, I liked the calculations of your future CpS...
