### ISSUE TITLE
next purchase timer

### ISSUE THREAD

**Issue by RuiApostolo** [greenc/CookieMaster#55]
next purchase timer doesn't take into account amount of cookies needed to stay above lucky+frenzy limit, if you have the maintain bank option turned on.

**Comment by greenc** [comment]
I am aware of this (check the release notes for v.1.16.0). Will look into incorporating the waiting period for Lucky bank into the timer in a future release.

**Comment by RuiApostolo** [comment]
Ah, last entrance, I see. didn't understand what it was when I read it ( I read it before making the change from 1.5.2 to 1.6.2)
