### ISSUE TITLE
Delay Golden Cookie sound trigger by ~1 second to allow for fade-in 

### ISSUE THREAD

**Issue by jsutan** [greenc/CookieMaster#6]
Currently the Golden Cookie sound trigger plays as soon as a Golden Cookie spawns, which is accurate, but because of the fade-in on the cookie it's generally about 1 to 2 seconds before it's actually visible.  

Could either delay the sound by 1-2 seconds or disable the fade-in, not sure which is optimal.

**Comment by llbit** [comment]
I think it works well as it is because it takes a while to react to the sound trigger (often in another tab/window).

**Comment by greenc** [comment]
I'm going to close this as I feel the sound trigger is accurate, and (for reindeer especially) it takes a second or two to react to the alert and switch tabs. Additionally, the fade-in effect for Golden Cookies doesn't actually apply during chains, so this has a limited scope regardless.
