### ISSUE TITLE
Time counters are too slow

### ISSUE THREAD

**Issue by worldendDominator** [greenc/CookieMaster#63]
Many time counters change several times slower than they should - in the time during which the timer changes by 1 second, 20-30 real seconds may pass.

Bugged timers include: time to lucky/lucky+frenzy bank; cookies to next heavenly chip and to X heavenly chips; all timers in building/upgrade popups (time till available, lucky/lucky+frenzy/chain deficit).

Timer for bank to next chain tier works somewhat correctly, except that it slows down with wrinklers' appearance - so it's twice as slow with 10 of them.

**Comment by worldendDominator** [comment]
It's fixed now.

**Comment by worldendDominator** [comment]
Apparently they still are affected by CpS withering. Everything was correct until wrinklers apeared.

Addition: Time estimations don't change when Frenzy is active; they just change their speed.

All in all, it seems that the timers are based on non-withered Frenzy CpS, and go slower whenever actual CpS is lower.

**Comment by super-aardvark** [comment]
They're actually based on Effective CpS.  I suppose we could add an option to use Base CpS instead (or a much shorter moving average).
