### ISSUE TITLE
Add timer for current season

### ISSUE THREAD

**Issue by jsutan** [greenc/CookieMaster#67]
Enhancement: Could you add a timer that shows you how much longer you have in the current season? 

Sometimes I hit Christmas at 10 am on a weekend and forget when the weekday comes around and want to know if I should retrigger the Christmas season before leaving for work at 8 am (since overlapping 2 hours < losing 6-8 hours non-Christmas).

**Comment by lucabondi** [comment]
There is. In the native Stats page under the Special section.

**Comment by jsutan** [comment]
Oh, right, forgot about that, but it would still be a userful timer bar to have with the other Cookie Master timer bars (with a setting in the Timers tab)
