### ISSUE TITLE
Suggestion: Elder Covenant cost

### ISSUE THREAD

**Issue by worldendDominator** [greenc/CookieMaster#68]
A calculation of how much you will lose from Elder Covenant penalty to CpS in the next half-hour and/or hour (depending on whether you have Sacrificial rolling pins, or both if the script can't check that). Based on current base CpS.
With this, you can determine whether it's cheaper to buy a Pledge or go with Covenant.

**Comment by Icehawk78** [comment]
While I'm sure CMa would be able to do this, without explicitly going out of your way to make it do so, it's effectively always cheaper to pledge than to buy the covenant, given the prerequisites to buying those upgrades in the first place.

**Comment by worldendDominator** [comment]
Well, true. Didn't think about that.
Closed then.
