### ISSUE TITLE
Golden Cookie sounds do not play

### ISSUE THREAD

**Issue by llbit** [greenc/CookieMaster#7]
After reloading recently golden cookie sounds stopped working. I'm unsure if this happened before 1.4.2, but I see that things have been hotfixed since the release so maybe something of that broke it.

The reindeer sounds do work. Tried downloading the cookie sound from the URL in the source and that works.

![bug](https://f.cloud.github.com/assets/2757386/1850890/6496ccf8-76de-11e3-8a3e-26809fd9fe1a.png)

**Comment by greenc** [comment]
That's a weird one, I can't seem to replicate it myself. It could possibly be that the external mp3 audio file was not available when you loaded the plugin (site down, etc.).

Can you try reloading CookieMaster and seeing if that fixes it?

Either way, I will probably move the audio files into the plugin itself in a future update so it's not relying on an external file to work correctly.

**Comment by llbit** [comment]
Now it works again, after reloading! I guess it might have just been that it couldn't fetch the sound then, but it is strange because I reloaded several times trying to fix it and then downloaded the sound from the site where it is hosted between the reloads.

**Comment by greenc** [comment]
I've moved the sound files directly into the plugin for the next release, which should prevent any issues like this from happening in the future.

**Comment by llbit** [comment]
Nice! Thanks!

**Comment by greenc** [comment]
That being said, I have just discovered that Chrome will sometimes refuse to play a sound more than once, so if you are using Chrome and find that the alerts only play the first time when loading the plugin, stay tuned as a fix should be imminent!

**Comment by llbit** [comment]
`Audio.load()` seems to fix it for me:

```
                    if(!gcNotified) {
                            gcAlert.load();
                            gcAlert.volume = 0.5;
                            gcAlert.play();
                            this.config.cmAudioGCNotified = true;
                    }
```

**Comment by greenc** [comment]
Yeah, I think this will be my temporary hotfix for the solution (for Chrome users). Unfortunately, it causes the browser to make a new request for the audio file each time it's called, which is 5 times per second! Chrome usually skips the cache and downloads the file repeatedly as well, which is not a good thing :(

**Comment by llbit** [comment]
That should only be called before the sound is played though, but yeah would be nice if it could be cached.

**Comment by greenc** [comment]
Very true, it's only called when the sound needs to play, so it's not too bad. Chrome still makes the network request each time though on the live site, which isn't ideal but it's fine for now.

The fix is live in v.1.5.3.
