### ISSUE TITLE
Completely broken

### ISSUE THREAD

**Issue by DocChloroplast** [greenc/CookieMaster#76]
I just reloaded version 1.17.1 on my Chrome browser, and it completely freezes up the game; the cookie does not appear, and nothing can be purchased.

I'm using Version 33.0.1750.154 m of Chrome.

EDIT: Oh geez, this post came out really entitled and jerkish. I sincerely apologize to the devs for my unwarranted attitude.

**Comment by Cruxador** [comment]
Yep, this is due to Orteil's new update.Hopefully it'll be fixed promptly.

**Comment by rashfael** [comment]
I wrote a fix, and I'll also be hosting the bookmarklet myself. @greenc doesn't seem to be active at github atm.

**Comment by rashfael** [comment]
I hosted the fixed version as a bookmarklet, simply use the bookmarklet from my branch
https://github.com/rashfael/CookieMaster/tree/selfhost#how-to-use

**Comment by DocChloroplast** [comment]
Thank you very much for your contributions to this. It's really appreciated.

**Comment by sranger** [comment]
Any news on supporting 1.0453?
