### ISSUE TITLE
One Mind Question Dialog can't be closed

### ISSUE THREAD

**Issue by rashfael** [greenc/CookieMaster#80]
When buying the One Mind upgrade, the question dialog asking whether you really want to start the grandmacopalypse can't be closed with any button. Not getting any exceptions on the console, it looks like it reopens immediately.

**Comment by rashfael** [comment]
Should work now, at least with autobuy, will reset and test again.

**Comment by lucabondi** [comment]
Works for Chrome but not in Firefox... console says... "ReferenceError: invalid assignment left-hand side       cookiemaster.min.js:2"

**Comment by rashfael** [comment]
I get this in Chrome too, after a reset.

**Comment by rashfael** [comment]
ok, this was either a complete brainfuck on my side, or my editor did something weird. replaces 'true' with 'time' and in the line below 'time' with 'true'.

**Comment by lucabondi** [comment]
Both working now. ;)
