### ISSUE TITLE
maximum cookie chain reward bug, while in frenzy

### ISSUE THREAD

**Issue by RuiApostolo** [greenc/CookieMaster#83]
sometimes, while on frenzy, the maximum cookie chain reward shows 778, although the "bank required for next chain tier" and "CpS required for next chain tier" are both green.
I suspect it happens when the bank has more cookies (i think something around more than 10 Z, but I will try to check that).

**Comment by rashfael** [comment]
I guess this could be related to #82 and a general problem with CookieClicker using ordinary javascript Number types, which are 64-bit floating point numbers, and those just get inaccurate with huge numbers.
