### ISSUE TITLE
Cannot Load Cookie Master 1.17.1

### ISSUE THREAD

**Issue by adamsalem** [greenc/CookieMaster#84]
Hey guys,

Using SRWare Iron (Chromium) using the Browser extension and getting these errors on page load:

```
Uncaught SyntaxError: Unexpected token else cookiemaster.min.js:1
CM.replaceNative cookiemaster.min.js:1
(anonymous function) cookiemaster.min.js:3
```

Also doesn't work using the bookmark method but comes up with a different error as below:

```
Uncaught TypeError: Cannot call method 'prepend' of null cookiemaster.min.js:3
CM.message cookiemaster.min.js:3
(anonymous function) cm-bootstrap.min.js?c=1397383559528:1
```

Other extensions are functioning as is Frozen Cookies but no dice with CM :s

Happy to work out issues if you have things to test, I'll make sure I'm subscribed to the issue so I get notifications.

**Comment by mugenzan** [comment]
greenc seems to be currently MIA, so there hasn't been an update since the april fools update which is what originally broke the code. rashfael has been nice enough to self-host working code in the meantime. If you use the bookmark or script to load cookie master, just change the part of the bookmark/script that says '//cookiemaster.co.uk/b?c=' with '//cookiemaster.creatale.de/b?c='. That version is stable and works.

**Comment by adamsalem** [comment]
Hrm, just done that and still get the

```
Uncaught TypeError: Cannot call method 'prepend' of null cookiemaster.min.js:3
CM.message cookiemaster.min.js:3
(anonymous function)
```

**Comment by rashfael** [comment]
Make sure to have disabled all old CookieMaster extensions.

**Comment by adamsalem** [comment]
Ahhh that was it, thanks rash!

**Comment by plim123** [comment]
I'm still getting the prepend error message even with the old extensions disabled...I've even tried rashfael's forked version of the script - still get the prepend error message on chrome on both.

any ideas?

oh, and thanks everyone for all the effort on cookie master!

**Comment by plim123** [comment]
oh, I take that back - my error is slightly different. it's still prepend, but something different:

Uncaught TypeError: Cannot read property 'prepend' of null cookiemaster.min.js?v=1.17.1:3

**Comment by rashfael** [comment]
Are you really sure you are running the correct bookmark and the newest version?
It should be 1.17.5 not 1.17.1

**Comment by plim123** [comment]
Thanks. I'll check tonight when I get home, but I was using the bookmark
method which points to whatever version is current on the server. But I'll
check it again tonight!

**Comment by plim123** [comment]
Ok, I don't know what happened. but it looks like chrome was somehow caching the old version, even though I had restarted the browser before. it's working now. thanks rashfael!
