### ISSUE TITLE
How do I get this to work? 

### ISSUE THREAD

**Issue by Joofyloops** [greenc/CookieMaster#86]
How do I get this to work? I'm on Windows 7, using chrome Version 34.0.1847.116 m. and Cookie Clicker version v.1.0453. In Chrome, I go to the Bookmarks Manager - Organize - Add Page. I set the URL as the script in the "How to use" section from "https://github.com/greenc/CookieMaster/blob/master/README.md" and enter a name of my choosing ("Cookies"). I open the "http://orteil.dashnet.org/cookieclicker/" website so my cookie clicker is going. I then click on the bookmark I set ("Cookies") and nothing happens. Meh?

**Comment by adamsalem** [comment]
Use the guide from here: https://github.com/rashfael/CookieMaster/tree/selfhost#how-to-use instead.

The main maintainer seems to be AFK at the moment so Rashfael is nicely keeping it up to date.

**Comment by Joofyloops** [comment]
Thanks - had no luck with that method, but managed to get the frozen cookie addon to work instead. Seems just as good.
