### ISSUE TITLE
Kitten Managers upgrade not being recognized - problem code found

### ISSUE THREAD

**Issue by raydawg2010** [greenc/CookieMaster#90]
The newest Kitten upgrade is not being used in any of the calculations that CM provides display values for, such as "Base CPS after Reset"

The kitten upgrades are hard coded in CM and the new "Kitten Manager" is missing in the following 2 places

CME.milkPotentials = {
    "Kitten helpers": .05,
    "Kitten workers": .1,
    "Kitten engineers": .2,
    "Kitten overseers": .2,
    "Santa's milk and cookies": .05

and then it is also missing in the the formula for the following function:

CM.getBaseMultiplier = function (a, b)  (formula to long to post)

The area that I notice this bug is in the ""Base CPS after Reset" display because my reset CPS is actually half of what my current CPS is, so i have a negative increase.

**Comment by rashfael** [comment]
The multiplier calculation and "Base CPS after Reset" should be correct again with a [fix](https://github.com/rashfael/CookieMaster/pull/1) by @mrtnnbr, which I uploaded just now.
The milkPotentials are not yet correct, thanks for the tip.
