### ISSUE TITLE
Method of simulating buy fundamentaly broken?

### ISSUE THREAD

**Issue by rashfael** [greenc/CookieMaster#96]
With the new easter update, simulating the egg upgrades kills the simulation. It seems to buy eggs forever and the simulating actions have consequences in other parts of the game now.
I have excluded all eggs from cost simulation completely for now.

**Comment by super-aardvark** [comment]
I think we can close this.  I didn't know there had been such a problem with them before, but I enabled simulation for most of the eggs and it works fine.

**Comment by rashfael** [comment]
Closing, since orteil fixed the problem with fake-buying upgrades having side effects.
