### ISSUE TITLE
Won't open

### ISSUE THREAD

**Issue by volcarona** [greenc/CookieMaster#97]
I have Cookie Master installed in Google Chrome and know it's installed correctly because the shorthand for the numbers is working (Qa) but I can't see any settings to do anything with it.

**Comment by rashfael** [comment]
Does the "Cookie Master X loaded successfully" pop up when you load it?

**Comment by vagrant326** [comment]
For me, on Opera, after clicking on saved tab with link to CM, only difference is Qi instead of quintillion, No pop ups, no new menu options, like nothing happened

**Comment by rashfael** [comment]
Haven't tested on Opera, could you tell me what's the output on the Developer Console?

**Comment by vagrant326** [comment]
"Unhandled Error: Function constructor: failed to compile function" in line 1036 of cookiemaster.min.js

**Comment by vagrant326** [comment]
And on my mozilla console pops out something like
[21:45:36.226] Uknown pseudoclss or pseudoelement „-webkit-slider-thumb”.  Collection of rules ignored because of wrong selector @ http://cookiemaster.co.uk/dist/cookiemaster.min.css?v=1.17.1:1
[21:45:36.226] Unknown property „-moz-touch-callout”.  Declaration omitted. @ http://cookiemaster.co.uk/dist/cookiemaster.min.css?v=1.17.1:1
[21:45:36.226] Unknown property „user-select”.  Declaration omitted. @ http://cookiemaster.co.uk/dist/cookiemaster.min.css?v=1.17.1:1
[21:45:36.250] SyntaxError: syntax error @ http://cookiemaster.co.uk/dist/cookiemaster.min.js?v=1.17.1:94
so it may be unrelated to browser
PS, Console log was translated and may be not 100% correct but i hope you`ll get the main problem.

**Comment by rashfael** [comment]
You are using the old, broken bookmarklet. Try [that one](https://github.com/rashfael/CookieMaster/tree/selfhost#how-to-use). I currently keep that up to date while @greenc is busy.

**Comment by volcarona** [comment]
Nothing pops up saying it loaded successfully. I'm not sure who you're talking to but I am not using a bookmarklet I am using the chrome extension. I am confused why other people are posting their issues on my issue..

**Comment by vagrant326** [comment]
I have had same symptoms and I thought i might help. Sorry for interrupting :)

**Comment by volcarona** [comment]
All I want is an alert when I get a golden cookie >_<

**Comment by rashfael** [comment]
What version are you using, @volcarona? The "official" version (1.7.1) is outdated and broken, I wrote some fixes and provide that bookmarklet. The information on cookiemaster.co.uk is outdated. If you want to use my fixes as an extension, try using [these instructions](http://www.reddit.com/r/CookieClicker/comments/229ssk/cookiemaster_fix_for_cookieclicker_v10417/).

**Comment by volcarona** [comment]
Downloaded the chrome extension from that post, it's actually showing up now, but it's super lagged. Is that normal?

**Comment by volcarona** [comment]
also I turned it off because of the lag and now I have infinity cookies XD

**Comment by rashfael** [comment]
There is a bug #96 with the easter update, although it should be fixed, at least with the bookmarklet. the extension doesn't seem to be the newest version. It is safe to use the bookmarklet, but with the extension [this happens](http://www.reddit.com/r/CookieClicker/comments/25va6j/psa_do_not_use_cookie_master_on_the_easter_update/). I see if I can release a new, fixed version of the extension soon.

**Comment by vagrant326** [comment]
Sorry for interrupting again but I cant find a better place to say this. There is an additional issue with Your version of CM. There is a shadow achievement for using addons. Why it`s not activated?

**Comment by rashfael** [comment]
The Addon has to explicitly call a function in Cookie Clicker and Cookie Master isn't doing that right now.

**Comment by volcarona** [comment]
well now my game is ruined.. awesome

**Comment by rashfael** [comment]
Sorry, the original maintainer of CookieMaster isn't updating it any more, I just try to keep things working most of the time.
