### ISSUE TITLE
Code structure

### ISSUE THREAD

**Issue by rashfael** [greenc/CookieMaster#98]
The main file (cookiemaster.js) is HUGE, and I'd like to split it up. Is there any technology that all maintainers are familiar with? I personally use [brunch](http://brunch.io) instead of grunt, but a module plugin (common.js for example) for grunt is also possible. Opinions, @greenc, @super-aardvark ?

**Comment by greenc** [comment]
Completely agree. I made a start at splitting it up in a separate branch - was going to just use a native module approach. Common.js might be a good approach though.

I'm likely not going to be able to contribute a lot in the future, so feel free to go with whatever you're most comfortable with.

Chris

**Comment by super-aardvark** [comment]
I've never used any kind of build process with javascript before this project, so I've got no opinion.  I'll just learn whatever you want to use.

**Comment by rashfael** [comment]
Ok, I'll evaluate the options and create a refactoring branch.
